---
- name: Install app binaries
  hosts: app-packer
  become: true
  tasks:
  - name: Install Ruby
    apt:
      name: ["ruby-full", "ruby-bundler", "build-essential"]
      state: present
      update_cache: yes
