- name: Configure mongodb
  become: true
  hosts: reddit-db-instances
  tags:
  - db-tag

  vars:
    mongod_bind_ip: "0.0.0.0"

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify:
    - restart_mongod

  handlers:
  - name: restart_mongod
    systemd:
      name: mongod
      state: restarted
      enabled: yes

- name: Configure App
  become: true
  hosts: reddit-app-instances
  tags:
  - app-tag

  vars:
    db_host: "{{ groups['reddit-db-instances'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | first }}"

  tasks:
  - name: Add unit file for puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify:
      - restart_puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /opt/db_config
    notify:
    - restart_puma

  handlers:
  - name: restart_puma
    service:
      name: puma
      state: restarted
      enabled: yes

- name: Deploy app
  hosts: reddit-app-instances
  become: true
  tags:
  - deploy-tag

  tasks:
  - name: Fetch the last version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /opt/reddit
      version: monolith
    notify:
    - restart_puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /opt/reddit

  handlers:
  - name: restart_puma
    service:
      name: puma
      state: restarted
      enabled: yes
