---
- name: Configure hosts & deploy application
  hosts: all
  become: true
  vars:
    mongod_bind_ip: "0.0.0.0"
    db_host: "{{ groups['reddit-db-instances'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | first }}"

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    tags:
      - db-tag
    notify:
    - restart_mongod

  - name: Add unit file for puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    tags:
      - app-tag
    notify:
      - restart_puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /opt/db_config
    tags:
    - app-tag
    notify:
    - restart_puma

  - name: Fetch the last version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /opt/reddit
      version: monolith
    tags:
    - deploy-tag
    notify:
    - restart_puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /opt/reddit
    tags:
    - deploy-tag

  handlers:
  - name: restart_mongod
    systemd:
      name: mongod
      state: restarted
      enabled: yes

  - name: restart_puma
    service:
      name: puma
      state: restarted
      enabled: yes
