---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment"

- name: Add unit file for puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify:
    - restart_puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /opt/db_config
  notify:
  - restart_puma
