- name: Configure mongodb
  become: true
  hosts: reddit-db-instances
  vars:
    mongod_bind_ip: "0.0.0.0"

  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify:
    - restart_mongod

  handlers:
  - name: restart_mongod
    systemd:
      name: mongod
      state: restarted
      enabled: yes
