---
- name: Install db binaries
  hosts: db-packer
  become: true
  tasks:
  - name: Add key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
      state: present

  - name: Install repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2.list

  - name: Install MongoDB
    apt: 
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Start & enable service
    systemd:
      name: mongod
      state: started
      enabled: true
